# This file contain all settings for the blog module.

# set languages for posts. -> One language is necessary.
languages:
  language_en:
    identifier: en
    title: English
  language_it:
    identifier: it
    title: Italiano

# set post fields for posts.
post_fields:
  relay:
    type: relay
    position: 1
    label: Example of Relay
    class: xs-12 sm-12 md-12 lg-12
    fields:
      text1:
        type: text
        label: Text
      image1:
        type: image
        label: Image
        class: md-4 lg-4

# set menu for the module.
menu:
  blog_articles:
    icon: newspaper-o
    title: translate[posts]
    url: /lato/blog/posts
    position: 3
    permission_min: 0
    permission_max: 99
    sub_items:
      new:
        title: translate[posts_new]
        url: /lato/blog/posts/new
        permission_min: 0
        permission_max: 99
      all:
        title: translate[posts_index]
        url: /lato/blog/posts
        permission_min: 0
        permission_max: 99
      categories:
        title: translate[posts_categories]
        url: /lato/blog/categories
        permission_min: 0
        permission_max: 99
  blog_documentation:
    icon: book
    title: translate[documentation]
    url: /lato/blog/doc
    position: 1002
    permission_min: 4
    permission_max: 99

# set assets for the module. -> Please, do not edit default assets.
assets:
  blog_style:
    path: lato_blog/application
    type: stylesheet
  blog_script:
    path: lato_blog/application
    type: javascript

# set widgets for the module. -> Please, do not edit default widgets.
widgets:
  blog_switch_lang:
    icon: flag
    path: lato_blog/widgets/switchlang
    position: 11

partials:
  media_media_selector:
    path: lato_blog/partials/relay-destroy-button
    position: 1
